# Generated by Django 3.2.3 on 2021-05-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todo_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='task',
        ),
    ]
